//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Fifth.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="FifthParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IFifthVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.fifth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFifth([NotNull] FifthParser.FifthContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.module_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule_import([NotNull] FifthParser.Module_importContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.module_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule_name([NotNull] FifthParser.Module_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.packagename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackagename([NotNull] FifthParser.PackagenameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlias([NotNull] FifthParser.AliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_declaration([NotNull] FifthParser.Function_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_body([NotNull] FifthParser.Function_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_name([NotNull] FifthParser.Function_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.variable_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_constraint([NotNull] FifthParser.Variable_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.paramdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamdecl([NotNull] FifthParser.ParamdeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.destructuring_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDestructuring_decl([NotNull] FifthParser.Destructuring_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.destructure_binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDestructure_binding([NotNull] FifthParser.Destructure_bindingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.class_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_definition([NotNull] FifthParser.Class_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.property_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProperty_declaration([NotNull] FifthParser.Property_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_name([NotNull] FifthParser.Type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.absoluteIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbsoluteIri([NotNull] FifthParser.AbsoluteIriContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] FifthParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] FifthParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] FifthParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_statement([NotNull] FifthParser.Assignment_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_statement([NotNull] FifthParser.Expression_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] FifthParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_statement([NotNull] FifthParser.Return_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_statement([NotNull] FifthParser.While_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.with_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWith_statement([NotNull] FifthParser.With_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_decl([NotNull] FifthParser.Var_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.var_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_name([NotNull] FifthParser.Var_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] FifthParser.ListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.list_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_body([NotNull] FifthParser.List_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.list_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_literal([NotNull] FifthParser.List_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.list_comprehension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_comprehension([NotNull] FifthParser.List_comprehensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.list_type_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_type_signature([NotNull] FifthParser.List_type_signatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.array_type_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_type_signature([NotNull] FifthParser.Array_type_signatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] FifthParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_mul</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_mul([NotNull] FifthParser.Exp_mulContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_and</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_and([NotNull] FifthParser.Exp_andContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_rel</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_rel([NotNull] FifthParser.Exp_relContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_operand</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_operand([NotNull] FifthParser.Exp_operandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_unary_postfix</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_unary_postfix([NotNull] FifthParser.Exp_unary_postfixContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_unary</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_unary([NotNull] FifthParser.Exp_unaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_exp</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_exp([NotNull] FifthParser.Exp_expContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_member_access</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_member_access([NotNull] FifthParser.Exp_member_accessContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_funccall</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_funccall([NotNull] FifthParser.Exp_funccallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_or</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_or([NotNull] FifthParser.Exp_orContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exp_add</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_add([NotNull] FifthParser.Exp_addContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.function_call_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call_expression([NotNull] FifthParser.Function_call_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperand([NotNull] FifthParser.OperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.object_instantiation_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_instantiation_expression([NotNull] FifthParser.Object_instantiation_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.initialiser_property_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitialiser_property_assignment([NotNull] FifthParser.Initialiser_property_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex([NotNull] FifthParser.IndexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.slice_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlice_([NotNull] FifthParser.Slice_Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lit_nil</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLit_nil([NotNull] FifthParser.Lit_nilContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lit_int</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLit_int([NotNull] FifthParser.Lit_intContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lit_bool</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLit_bool([NotNull] FifthParser.Lit_boolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lit_string</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLit_string([NotNull] FifthParser.Lit_stringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>lit_float</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLit_float([NotNull] FifthParser.Lit_floatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>str_plain</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStr_plain([NotNull] FifthParser.Str_plainContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>str_interpolated</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStr_interpolated([NotNull] FifthParser.Str_interpolatedContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>str_raw</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStr_raw([NotNull] FifthParser.Str_rawContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean([NotNull] FifthParser.BooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>num_decimal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum_decimal([NotNull] FifthParser.Num_decimalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>num_binary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum_binary([NotNull] FifthParser.Num_binaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>num_octal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum_octal([NotNull] FifthParser.Num_octalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>num_hex</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum_hex([NotNull] FifthParser.Num_hexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>num_imaginary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum_imaginary([NotNull] FifthParser.Num_imaginaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>num_rune</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum_rune([NotNull] FifthParser.Num_runeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.operandName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperandName([NotNull] FifthParser.OperandNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="FifthParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedIdent([NotNull] FifthParser.QualifiedIdentContext context);
}
