using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace AstSourceGenerators;

[Generator]
public class SimpleTestGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Just create a simple test file to verify the generator is working
        context.RegisterPostInitializationOutput(ctx =>
        {
            var testSource = @"
// Generated by SimpleTestGenerator
namespace ast_generated
{
    public class TestGeneratedClass
    {
        public string Message => ""Hello from Source Generator!"";
    }
}";
            ctx.AddSource("test.generated.cs", SourceText.From(testSource, Encoding.UTF8));
        });
    }
}

