using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace AstSourceGenerators;

[Generator]
public class SimpleAstGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // For now, just generate a simple test file to verify the generator works
        context.RegisterPostInitializationOutput(static ctx =>
        {
            var source = @"// This file was generated by SimpleAstGenerator
// Generated at: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss") + @"

namespace ast_generated;

public static class GeneratedTest 
{
    public static string Message => ""Source generators are working!"";
}
";
            ctx.AddSource("test.generated.cs", SourceText.From(source, Encoding.UTF8));
        });
    }
}