// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ast_generator
{
    using System;
    using System.Dynamic;
    using System.Linq;
    using System.Reflection;
    using System.Text;
    using System.Text.Json;
    using System.Collections.Generic;
    using ast_model;
    using ast;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\AstVisitors.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class AstVisitors : AstVisitorsBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 14 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.metamodel.ttinclude"

    // TextTemplatingFileGenerator
    var ns = TypeProvider.NamespaceScope;
    var allTypes = TypeProvider.AllAstTypes;
    var nonIgnoredTypes = TypeProvider.NonIgnoredTypes;
    var concreteTypes = TypeProvider.ConcreteTypes;
    var asts = concreteTypes;

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 1 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"

    var genNs = ns + "_generated";

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 4 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(genNs));
            
            #line default
            #line hidden
            this.Write(";\r\nusing ");
            
            #line 5 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ns));
            
            #line default
            #line hidden
            this.Write(";\r\nusing System.Collections.Generic;\r\n\r\npublic interface IAstVisitor\r\n{\r\n");
            
            #line 10 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
 foreach (var ast in asts)  { 
            
            #line default
            #line hidden
            this.Write("    public void Enter");
            
            #line 11 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ast.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 11 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ast.Name));
            
            #line default
            #line hidden
            this.Write(" ctx);\r\n    public void Leave");
            
            #line 12 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ast.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 12 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ast.Name));
            
            #line default
            #line hidden
            this.Write(" ctx);\r\n");
            
            #line 13 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\npublic partial class BaseAstVisitor : IAstVisitor\r\n{\r\n");
            
            #line 18 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
 foreach (var ast in asts)  { 
            
            #line default
            #line hidden
            this.Write("    public virtual void Enter");
            
            #line 19 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ast.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 19 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ast.Name));
            
            #line default
            #line hidden
            this.Write(" ctx){}\r\n    public virtual void Leave");
            
            #line 20 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ast.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 20 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ast.Name));
            
            #line default
            #line hidden
            this.Write(" ctx){}\r\n");
            
            #line 21 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n\r\npublic interface IAstRecursiveDescentVisitor\r\n{\r\n    public AstThing Visit" +
                    "(AstThing ctx);\r\n");
            
            #line 28 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
 foreach (var ast in asts)  { 
            
            #line default
            #line hidden
            this.Write("    public ");
            
            #line 29 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ast.Name));
            
            #line default
            #line hidden
            this.Write(" Visit");
            
            #line 29 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ast.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 29 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ast.Name));
            
            #line default
            #line hidden
            this.Write(" ctx);\r\n");
            
            #line 30 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\npublic class DefaultRecursiveDescentVisitor : IAstRecursiveDescentVisitor\r\n{" +
                    "\r\n    public virtual AstThing Visit(AstThing ctx){\r\n        if(ctx == null) retu" +
                    "rn ctx;\r\n        return ctx switch\r\n        {\r\n");
            
            #line 39 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
 foreach (string astNodeType in asts.Select(a=>a.Name))  { 
            
            #line default
            #line hidden
            this.Write("             ");
            
            #line 40 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(astNodeType));
            
            #line default
            #line hidden
            this.Write(" node => Visit");
            
            #line 40 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(astNodeType));
            
            #line default
            #line hidden
            this.Write("(node),\r\n");
            
            #line 41 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n            { } node => null,\r\n        };\r\n    }\r\n\r\n");
            
            #line 47 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"


foreach (var ast in asts)
{
    var allProps = ast.VisitableProperties();

            
            #line default
            #line hidden
            this.Write("    public virtual ");
            
            #line 53 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ast.Name));
            
            #line default
            #line hidden
            this.Write(" Visit");
            
            #line 53 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ast.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 53 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(ast.Name));
            
            #line default
            #line hidden
            this.Write(" ctx)\r\n    {\r\n");
            
            #line 55 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"

    foreach(var prop in allProps.Where(p => p.PropertyType.IsCollectionType()))
    {
        var varName = $"tmp{prop.Name}";
        var propTypeName = prop.PropertyType.BuildTypeName();
        var propInstTypeName = prop.PropertyType.TypeParameter(0);

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 62 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(propTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 62 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(varName));
            
            #line default
            #line hidden
            this.Write(" = [];\r\n        ");
            
            #line 63 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(varName));
            
            #line default
            #line hidden
            this.Write(".AddRange(ctx.");
            
            #line 63 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(".Select(x => (");
            
            #line 63 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(propInstTypeName));
            
            #line default
            #line hidden
            this.Write(")Visit(x)));\r\n");
            
            #line 64 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"

    } // for all collection properties

            
            #line default
            #line hidden
            this.Write("     return ctx with {\r\n");
            
            #line 68 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"

    string sep = " ";
    foreach (var prop in allProps)
    {
        if(prop.PropertyType.IsCollectionType())
        {
        var varName = $"tmp{prop.Name}";

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 76 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(sep));
            
            #line default
            #line hidden
            
            #line 76 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 76 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(varName));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 77 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"

        }
        else
        {
            var propTypeName = prop.PropertyType.BuildTypeName();

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 83 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(sep));
            
            #line default
            #line hidden
            
            #line 83 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 83 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(propTypeName));
            
            #line default
            #line hidden
            this.Write(")Visit((AstThing)ctx.");
            
            #line 83 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 84 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"

        }
        sep = ",";
    } // foreach prop


            
            #line default
            #line hidden
            this.Write("        };\r\n    }\r\n");
            
            #line 92 "C:\dev\aabs\5th-related\ast-builder\src\ast_generator\ast.visitors.ttinclude"

} // foreach ast

            
            #line default
            #line hidden
            this.Write("\r\n}\r\n\r\n");
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class AstVisitorsBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
