//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/FifthParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FifthParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IFifthParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.fifth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFifth([NotNull] FifthParser.FifthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.fifth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFifth([NotNull] FifthParser.FifthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.module_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule_import([NotNull] FifthParser.Module_importContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.module_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule_import([NotNull] FifthParser.Module_importContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.module_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule_name([NotNull] FifthParser.Module_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.module_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule_name([NotNull] FifthParser.Module_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.packagename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPackagename([NotNull] FifthParser.PackagenameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.packagename"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPackagename([NotNull] FifthParser.PackagenameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlias([NotNull] FifthParser.AliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlias([NotNull] FifthParser.AliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_declaration([NotNull] FifthParser.Function_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_declaration([NotNull] FifthParser.Function_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_body([NotNull] FifthParser.Function_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_body([NotNull] FifthParser.Function_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_name([NotNull] FifthParser.Function_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_name([NotNull] FifthParser.Function_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.variable_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_constraint([NotNull] FifthParser.Variable_constraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.variable_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_constraint([NotNull] FifthParser.Variable_constraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.paramdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamdecl([NotNull] FifthParser.ParamdeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.paramdecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamdecl([NotNull] FifthParser.ParamdeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.destructuring_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDestructuring_decl([NotNull] FifthParser.Destructuring_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.destructuring_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDestructuring_decl([NotNull] FifthParser.Destructuring_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.destructure_binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDestructure_binding([NotNull] FifthParser.Destructure_bindingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.destructure_binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDestructure_binding([NotNull] FifthParser.Destructure_bindingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.class_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_definition([NotNull] FifthParser.Class_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.class_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_definition([NotNull] FifthParser.Class_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.property_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_declaration([NotNull] FifthParser.Property_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.property_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_declaration([NotNull] FifthParser.Property_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_name([NotNull] FifthParser.Type_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_name([NotNull] FifthParser.Type_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.absoluteIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbsoluteIri([NotNull] FifthParser.AbsoluteIriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.absoluteIri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbsoluteIri([NotNull] FifthParser.AbsoluteIriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] FifthParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] FifthParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmt_ifelse</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt_ifelse([NotNull] FifthParser.Stmt_ifelseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmt_ifelse</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt_ifelse([NotNull] FifthParser.Stmt_ifelseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmt_while</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt_while([NotNull] FifthParser.Stmt_whileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmt_while</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt_while([NotNull] FifthParser.Stmt_whileContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmt_with</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt_with([NotNull] FifthParser.Stmt_withContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmt_with</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt_with([NotNull] FifthParser.Stmt_withContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmt_vardecl</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt_vardecl([NotNull] FifthParser.Stmt_vardeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmt_vardecl</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt_vardecl([NotNull] FifthParser.Stmt_vardeclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmt_bareexpression</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt_bareexpression([NotNull] FifthParser.Stmt_bareexpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmt_bareexpression</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt_bareexpression([NotNull] FifthParser.Stmt_bareexpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmt_assignment</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt_assignment([NotNull] FifthParser.Stmt_assignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmt_assignment</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt_assignment([NotNull] FifthParser.Stmt_assignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stmt_return</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt_return([NotNull] FifthParser.Stmt_returnContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stmt_return</c>
	/// labeled alternative in <see cref="FifthParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt_return([NotNull] FifthParser.Stmt_returnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_decl([NotNull] FifthParser.Var_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_decl([NotNull] FifthParser.Var_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.var_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_name([NotNull] FifthParser.Var_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.var_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_name([NotNull] FifthParser.Var_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] FifthParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] FifthParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EListLiteral</c>
	/// labeled alternative in <see cref="FifthParser.list_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEListLiteral([NotNull] FifthParser.EListLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EListLiteral</c>
	/// labeled alternative in <see cref="FifthParser.list_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEListLiteral([NotNull] FifthParser.EListLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EListComprehension</c>
	/// labeled alternative in <see cref="FifthParser.list_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEListComprehension([NotNull] FifthParser.EListComprehensionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EListComprehension</c>
	/// labeled alternative in <see cref="FifthParser.list_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEListComprehension([NotNull] FifthParser.EListComprehensionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_comp_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_comp_constraint([NotNull] FifthParser.List_comp_constraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_comp_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_comp_constraint([NotNull] FifthParser.List_comp_constraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_comp_generator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_comp_generator([NotNull] FifthParser.List_comp_generatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_comp_generator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_comp_generator([NotNull] FifthParser.List_comp_generatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_literal([NotNull] FifthParser.List_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_literal([NotNull] FifthParser.List_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_comprehension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_comprehension([NotNull] FifthParser.List_comprehensionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_comprehension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_comprehension([NotNull] FifthParser.List_comprehensionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_type_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_type_signature([NotNull] FifthParser.List_type_signatureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_type_signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_type_signature([NotNull] FifthParser.List_type_signatureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] FifthParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] FifthParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_mul</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_mul([NotNull] FifthParser.Exp_mulContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_mul</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_mul([NotNull] FifthParser.Exp_mulContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_and</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_and([NotNull] FifthParser.Exp_andContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_and</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_and([NotNull] FifthParser.Exp_andContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_rel</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_rel([NotNull] FifthParser.Exp_relContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_rel</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_rel([NotNull] FifthParser.Exp_relContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_operand</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_operand([NotNull] FifthParser.Exp_operandContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_operand</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_operand([NotNull] FifthParser.Exp_operandContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_unary</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_unary([NotNull] FifthParser.Exp_unaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_unary</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_unary([NotNull] FifthParser.Exp_unaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_exp</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_exp([NotNull] FifthParser.Exp_expContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_exp</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_exp([NotNull] FifthParser.Exp_expContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_funccall</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_funccall([NotNull] FifthParser.Exp_funccallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_funccall</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_funccall([NotNull] FifthParser.Exp_funccallContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_member_access</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_member_access([NotNull] FifthParser.Exp_member_accessContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_member_access</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_member_access([NotNull] FifthParser.Exp_member_accessContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_or</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_or([NotNull] FifthParser.Exp_orContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_or</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_or([NotNull] FifthParser.Exp_orContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_add</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_add([NotNull] FifthParser.Exp_addContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_add</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_add([NotNull] FifthParser.Exp_addContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_call_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_call_expression([NotNull] FifthParser.Function_call_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_call_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_call_expression([NotNull] FifthParser.Function_call_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperand([NotNull] FifthParser.OperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperand([NotNull] FifthParser.OperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.object_instantiation_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject_instantiation_expression([NotNull] FifthParser.Object_instantiation_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.object_instantiation_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject_instantiation_expression([NotNull] FifthParser.Object_instantiation_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.initialiser_property_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitialiser_property_assignment([NotNull] FifthParser.Initialiser_property_assignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.initialiser_property_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitialiser_property_assignment([NotNull] FifthParser.Initialiser_property_assignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex([NotNull] FifthParser.IndexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex([NotNull] FifthParser.IndexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.slice_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlice_([NotNull] FifthParser.Slice_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.slice_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlice_([NotNull] FifthParser.Slice_Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_nil</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLit_nil([NotNull] FifthParser.Lit_nilContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_nil</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLit_nil([NotNull] FifthParser.Lit_nilContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_int</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLit_int([NotNull] FifthParser.Lit_intContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_int</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLit_int([NotNull] FifthParser.Lit_intContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_bool</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLit_bool([NotNull] FifthParser.Lit_boolContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_bool</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLit_bool([NotNull] FifthParser.Lit_boolContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_string</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLit_string([NotNull] FifthParser.Lit_stringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_string</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLit_string([NotNull] FifthParser.Lit_stringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_float</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLit_float([NotNull] FifthParser.Lit_floatContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_float</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLit_float([NotNull] FifthParser.Lit_floatContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>str_raw</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStr_raw([NotNull] FifthParser.Str_rawContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>str_raw</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStr_raw([NotNull] FifthParser.Str_rawContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>str_interpolated</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStr_interpolated([NotNull] FifthParser.Str_interpolatedContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>str_interpolated</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStr_interpolated([NotNull] FifthParser.Str_interpolatedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean([NotNull] FifthParser.BooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean([NotNull] FifthParser.BooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>num_decimal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum_decimal([NotNull] FifthParser.Num_decimalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>num_decimal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum_decimal([NotNull] FifthParser.Num_decimalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>num_binary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum_binary([NotNull] FifthParser.Num_binaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>num_binary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum_binary([NotNull] FifthParser.Num_binaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>num_octal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum_octal([NotNull] FifthParser.Num_octalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>num_octal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum_octal([NotNull] FifthParser.Num_octalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>num_hex</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum_hex([NotNull] FifthParser.Num_hexContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>num_hex</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum_hex([NotNull] FifthParser.Num_hexContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>num_imaginary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum_imaginary([NotNull] FifthParser.Num_imaginaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>num_imaginary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum_imaginary([NotNull] FifthParser.Num_imaginaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>num_rune</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum_rune([NotNull] FifthParser.Num_runeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>num_rune</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum_rune([NotNull] FifthParser.Num_runeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.operandName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperandName([NotNull] FifthParser.OperandNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.operandName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperandName([NotNull] FifthParser.OperandNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedIdent([NotNull] FifthParser.QualifiedIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedIdent([NotNull] FifthParser.QualifiedIdentContext context);
}
