//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/FifthParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IFifthParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class FifthParserBaseListener : IFifthParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.fifth"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFifth([NotNull] FifthParser.FifthContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.fifth"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFifth([NotNull] FifthParser.FifthContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.module_import"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule_import([NotNull] FifthParser.Module_importContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.module_import"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule_import([NotNull] FifthParser.Module_importContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.module_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule_name([NotNull] FifthParser.Module_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.module_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule_name([NotNull] FifthParser.Module_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.packagename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPackagename([NotNull] FifthParser.PackagenameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.packagename"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPackagename([NotNull] FifthParser.PackagenameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlias([NotNull] FifthParser.AliasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlias([NotNull] FifthParser.AliasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_declaration([NotNull] FifthParser.Function_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_declaration([NotNull] FifthParser.Function_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_body([NotNull] FifthParser.Function_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_body([NotNull] FifthParser.Function_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_name([NotNull] FifthParser.Function_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_name([NotNull] FifthParser.Function_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.variable_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_constraint([NotNull] FifthParser.Variable_constraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.variable_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_constraint([NotNull] FifthParser.Variable_constraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.paramdecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamdecl([NotNull] FifthParser.ParamdeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.paramdecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamdecl([NotNull] FifthParser.ParamdeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.destructuring_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDestructuring_decl([NotNull] FifthParser.Destructuring_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.destructuring_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDestructuring_decl([NotNull] FifthParser.Destructuring_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.destructure_binding"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDestructure_binding([NotNull] FifthParser.Destructure_bindingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.destructure_binding"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDestructure_binding([NotNull] FifthParser.Destructure_bindingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.class_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_definition([NotNull] FifthParser.Class_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.class_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_definition([NotNull] FifthParser.Class_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.property_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_declaration([NotNull] FifthParser.Property_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.property_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_declaration([NotNull] FifthParser.Property_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.type_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_name([NotNull] FifthParser.Type_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.type_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_name([NotNull] FifthParser.Type_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.absoluteIri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbsoluteIri([NotNull] FifthParser.AbsoluteIriContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.absoluteIri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbsoluteIri([NotNull] FifthParser.AbsoluteIriContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] FifthParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] FifthParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.blockItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockItem([NotNull] FifthParser.BlockItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.blockItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockItem([NotNull] FifthParser.BlockItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] FifthParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] FifthParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] FifthParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] FifthParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.assignment_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_statement([NotNull] FifthParser.Assignment_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.assignment_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_statement([NotNull] FifthParser.Assignment_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.expression_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_statement([NotNull] FifthParser.Expression_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.expression_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_statement([NotNull] FifthParser.Expression_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] FifthParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] FifthParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_statement([NotNull] FifthParser.Return_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_statement([NotNull] FifthParser.Return_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.while_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_statement([NotNull] FifthParser.While_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.while_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_statement([NotNull] FifthParser.While_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.with_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWith_statement([NotNull] FifthParser.With_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.with_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWith_statement([NotNull] FifthParser.With_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.var_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_decl([NotNull] FifthParser.Var_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.var_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_decl([NotNull] FifthParser.Var_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.var_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_name([NotNull] FifthParser.Var_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.var_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_name([NotNull] FifthParser.Var_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] FifthParser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] FifthParser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EListLiteral</c>
	/// labeled alternative in <see cref="FifthParser.list_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEListLiteral([NotNull] FifthParser.EListLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EListLiteral</c>
	/// labeled alternative in <see cref="FifthParser.list_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEListLiteral([NotNull] FifthParser.EListLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EListComprehension</c>
	/// labeled alternative in <see cref="FifthParser.list_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEListComprehension([NotNull] FifthParser.EListComprehensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EListComprehension</c>
	/// labeled alternative in <see cref="FifthParser.list_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEListComprehension([NotNull] FifthParser.EListComprehensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_comp_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList_comp_constraint([NotNull] FifthParser.List_comp_constraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_comp_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList_comp_constraint([NotNull] FifthParser.List_comp_constraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_comp_generator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList_comp_generator([NotNull] FifthParser.List_comp_generatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_comp_generator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList_comp_generator([NotNull] FifthParser.List_comp_generatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList_literal([NotNull] FifthParser.List_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList_literal([NotNull] FifthParser.List_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_comprehension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList_comprehension([NotNull] FifthParser.List_comprehensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_comprehension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList_comprehension([NotNull] FifthParser.List_comprehensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.list_type_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList_type_signature([NotNull] FifthParser.List_type_signatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.list_type_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList_type_signature([NotNull] FifthParser.List_type_signatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] FifthParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] FifthParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_mul</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_mul([NotNull] FifthParser.Exp_mulContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_mul</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_mul([NotNull] FifthParser.Exp_mulContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_and</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_and([NotNull] FifthParser.Exp_andContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_and</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_and([NotNull] FifthParser.Exp_andContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_rel</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_rel([NotNull] FifthParser.Exp_relContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_rel</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_rel([NotNull] FifthParser.Exp_relContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_operand</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_operand([NotNull] FifthParser.Exp_operandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_operand</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_operand([NotNull] FifthParser.Exp_operandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_unary_postfix</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_unary_postfix([NotNull] FifthParser.Exp_unary_postfixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_unary_postfix</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_unary_postfix([NotNull] FifthParser.Exp_unary_postfixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_unary</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_unary([NotNull] FifthParser.Exp_unaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_unary</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_unary([NotNull] FifthParser.Exp_unaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_exp</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_exp([NotNull] FifthParser.Exp_expContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_exp</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_exp([NotNull] FifthParser.Exp_expContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_member_access</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_member_access([NotNull] FifthParser.Exp_member_accessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_member_access</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_member_access([NotNull] FifthParser.Exp_member_accessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_funccall</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_funccall([NotNull] FifthParser.Exp_funccallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_funccall</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_funccall([NotNull] FifthParser.Exp_funccallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_or</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_or([NotNull] FifthParser.Exp_orContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_or</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_or([NotNull] FifthParser.Exp_orContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exp_add</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_add([NotNull] FifthParser.Exp_addContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exp_add</c>
	/// labeled alternative in <see cref="FifthParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_add([NotNull] FifthParser.Exp_addContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.function_call_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_call_expression([NotNull] FifthParser.Function_call_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.function_call_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_call_expression([NotNull] FifthParser.Function_call_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperand([NotNull] FifthParser.OperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperand([NotNull] FifthParser.OperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.object_instantiation_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject_instantiation_expression([NotNull] FifthParser.Object_instantiation_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.object_instantiation_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject_instantiation_expression([NotNull] FifthParser.Object_instantiation_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.initialiser_property_assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitialiser_property_assignment([NotNull] FifthParser.Initialiser_property_assignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.initialiser_property_assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitialiser_property_assignment([NotNull] FifthParser.Initialiser_property_assignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.index"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndex([NotNull] FifthParser.IndexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.index"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndex([NotNull] FifthParser.IndexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.slice_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSlice_([NotNull] FifthParser.Slice_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.slice_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSlice_([NotNull] FifthParser.Slice_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_nil</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLit_nil([NotNull] FifthParser.Lit_nilContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_nil</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLit_nil([NotNull] FifthParser.Lit_nilContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_int</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLit_int([NotNull] FifthParser.Lit_intContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_int</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLit_int([NotNull] FifthParser.Lit_intContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_bool</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLit_bool([NotNull] FifthParser.Lit_boolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_bool</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLit_bool([NotNull] FifthParser.Lit_boolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_string</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLit_string([NotNull] FifthParser.Lit_stringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_string</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLit_string([NotNull] FifthParser.Lit_stringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>lit_float</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLit_float([NotNull] FifthParser.Lit_floatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>lit_float</c>
	/// labeled alternative in <see cref="FifthParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLit_float([NotNull] FifthParser.Lit_floatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>str_plain</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStr_plain([NotNull] FifthParser.Str_plainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>str_plain</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStr_plain([NotNull] FifthParser.Str_plainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>str_interpolated</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStr_interpolated([NotNull] FifthParser.Str_interpolatedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>str_interpolated</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStr_interpolated([NotNull] FifthParser.Str_interpolatedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>str_raw</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStr_raw([NotNull] FifthParser.Str_rawContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>str_raw</c>
	/// labeled alternative in <see cref="FifthParser.string_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStr_raw([NotNull] FifthParser.Str_rawContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean([NotNull] FifthParser.BooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean([NotNull] FifthParser.BooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>num_decimal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNum_decimal([NotNull] FifthParser.Num_decimalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>num_decimal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNum_decimal([NotNull] FifthParser.Num_decimalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>num_binary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNum_binary([NotNull] FifthParser.Num_binaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>num_binary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNum_binary([NotNull] FifthParser.Num_binaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>num_octal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNum_octal([NotNull] FifthParser.Num_octalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>num_octal</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNum_octal([NotNull] FifthParser.Num_octalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>num_hex</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNum_hex([NotNull] FifthParser.Num_hexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>num_hex</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNum_hex([NotNull] FifthParser.Num_hexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>num_imaginary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNum_imaginary([NotNull] FifthParser.Num_imaginaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>num_imaginary</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNum_imaginary([NotNull] FifthParser.Num_imaginaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>num_rune</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNum_rune([NotNull] FifthParser.Num_runeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>num_rune</c>
	/// labeled alternative in <see cref="FifthParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNum_rune([NotNull] FifthParser.Num_runeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.operandName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperandName([NotNull] FifthParser.OperandNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.operandName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperandName([NotNull] FifthParser.OperandNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FifthParser.qualifiedIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedIdent([NotNull] FifthParser.QualifiedIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FifthParser.qualifiedIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedIdent([NotNull] FifthParser.QualifiedIdentContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
