name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Nightly at 03:00 UTC

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Java 17 (for ANTLR)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify tool versions
        shell: bash
        run: |
          dotnet --info
          java -version

      - name: Restore
        run: dotnet restore fifthlang.sln

      - name: Check generated folder consistency
        shell: bash
        run: |
          set -euo pipefail
          tmp_dir="$(mktemp -d)"
          dotnet run --project src/ast_generator/ast_generator.csproj -- --folder "$tmp_dir"
          diff -ru src/ast-generated "$tmp_dir" > diff.txt || true
          if [ -s diff.txt ]; then
            echo 'Generated code differs from generator output.' >&2
            echo 'Do not hand-edit files in src/ast-generated; update metamodel/templates and regenerate.' >&2
            sed -n '1,200p' diff.txt >&2
            exit 1
          fi

      - name: Build
        run: dotnet build fifthlang.sln --configuration Release --no-restore

      - name: Run AST tests
        run: |
          dotnet test test/ast-tests/ast_tests.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=ast-tests.trx" \
            --results-directory "TestResults/ast-tests" \
            --collect:"XPlat Code Coverage" \
            --settings fifth.runsettings

      - name: Run all tests (solution)
        run: |
          dotnet test fifthlang.sln \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=solution.trx" \
            --results-directory "TestResults/solution" \
            --collect:"XPlat Code Coverage" \
            --settings fifth.runsettings

      - name: List TRX and coverage
        if: always()
        shell: bash
        run: |
          echo "TRX files:" && ls -1 TestResults/**/*.trx 2>/dev/null || true
          echo "Coverage (cobertura):" && ls -1 **/coverage.cobertura.xml 2>/dev/null || true

      - name: Upload TRX results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.os }}
          path: TestResults/**/*.trx
          if-no-files-found: warn

      - name: Install ReportGenerator
        if: always()
        shell: bash
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Generate Coverage Report
        if: always()
        shell: bash
        run: |
          if compgen -G "**/coverage.cobertura.xml" > /dev/null; then
            reportgenerator \
              -reports:**/coverage.cobertura.xml \
              -targetdir:CoverageReport \
              -reporttypes:Html;Cobertura;TextSummary
            echo "\nCoverage summary (partial):\n" >> $GITHUB_STEP_SUMMARY
            if [ -f CoverageReport/Summary.txt ]; then head -n 50 CoverageReport/Summary.txt >> $GITHUB_STEP_SUMMARY; fi
          else
            echo "No coverage files found; skipping report generation." | tee -a $GITHUB_STEP_SUMMARY
            mkdir -p CoverageReport
          fi

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-${{ matrix.os }}
          path: |
            CoverageReport/**
            **/coverage.cobertura.xml
          if-no-files-found: warn

